name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # 每天 0 点 UTC

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          TIME_RANGE: all_time
          SHOW_TOTAL: true
          SHOW_TITLE: true

